/**
 * Gateway Protocol V2 — Preload bridge
 * ───────────────────────────────────────────────────────────────
 * Exposes a narrow window.gp API to the renderer via contextBridge.
 * The renderer cannot reach Node, https, or fs — only these methods.
 *
 * Renderer usage (drop-in for the V1 fetch() calls):
 *
 *   const audioBuf = await window.gp.elevenlabsTTS({text, voiceId, ...});
 *   const blob = new Blob([audioBuf], { type: 'audio/mpeg' });
 *
 *   const data = await window.gp.mirror({ entry });
 *
 *   await window.gp.keys.set('anthropic', key);
 *   const has = await window.gp.keys.has('anthropic');
 * ───────────────────────────────────────────────────────────────
 */

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gp', {
  // Feature flag the HTML uses to pick Electron path vs proxy fallback
  isElectron: true,
  platform: process.platform,
  versions: { electron: process.versions.electron, chrome: process.versions.chrome, node: process.versions.node },

  // TTS — both return ArrayBuffer of audio/mpeg bytes
  elevenlabsTTS: (opts) => ipcRenderer.invoke('gp:elevenlabs-tts', opts),
  openaiTTS:     (opts) => ipcRenderer.invoke('gp:openai-tts', opts),

  // Quantum Mirror — returns parsed Anthropic JSON
  mirror: (opts) => ipcRenderer.invoke('gp:mirror', opts),

  // Adaptive Session Engine — Council reads last 7 journal entries,
  // returns { recommendedWave, recommendedFreq, recommendedBreath, intention, rationale }
  preSession: (opts) => ipcRenderer.invoke('gp:pre-session', opts),

  // V4a — Monthly pattern recognition across all journal entries
  monthlyPatterns: (opts) => ipcRenderer.invoke('gp:monthly-patterns', opts),

  // V4b — Custom affirmation generated by the Council
  generateAffirmation: (opts) => ipcRenderer.invoke('gp:generate-affirmation', opts),

  // V4c — Multi-turn shadow work dialogue with Jung
  shadowDialogue: (opts) => ipcRenderer.invoke('gp:shadow-dialogue', opts),

  // V4d — AI pattern analysis over a synchronicity log
  analyzeSynchronicities: (opts) => ipcRenderer.invoke('gp:analyze-synchronicities', opts),

  // V4f — Practice reminders (scheduled in main process, fires native notifications)
  reminders: {
    get: ()       => ipcRenderer.invoke('gp:reminders-get'),
    set: (cfg)    => ipcRenderer.invoke('gp:reminders-set', cfg),
  },

  // V7 — Network: Practice Rooms server URL + feed auto-share preference
  network: {
    get: ()       => ipcRenderer.invoke('gp:network-get'),
    set: (cfg)    => ipcRenderer.invoke('gp:network-set', cfg),
  },

  // V7c — OpenAI text embedding for semantic journal memory
  embed: (opts)   => ipcRenderer.invoke('gp:embed', opts),

  // V7c — Mirror call with retrieved past entries as context
  mirrorWithContext: (opts) => ipcRenderer.invoke('gp:mirror-with-context', opts),

  // Encrypted API key storage (electron-store backed)
  keys: {
    get: (name)        => ipcRenderer.invoke('gp:key-get', name),
    set: (name, value) => ipcRenderer.invoke('gp:key-set', name, value),
    has: (name)        => ipcRenderer.invoke('gp:key-has', name),
  },
});
