import fs from 'node:fs';

const tpl = fs.readFileSync('scripts/landing-source.html', 'utf8');

// ── 1. extract the design CSS (the 2nd <style> block; the 1st is inlined fonts we drop) ──
const firstStyle = tpl.indexOf('<style>');
const secondStyle = tpl.indexOf('<style>', firstStyle + 1);
const cssStart = secondStyle + '<style>'.length;
const cssEnd = tpl.indexOf('</style>', cssStart);
const CSS = tpl.slice(cssStart, cssEnd).trim();

// ── 2. extract verbatim body chunks by comment markers ──
const slice = (a, b) => tpl.slice(tpl.indexOf(a), tpl.indexOf(b));
const INTRO_AURA = slice('<!-- cinematic intro overlay -->', '<!-- ───────── chrome');
const THRESHOLD  = slice('<!-- ───────── threshold', '<!-- ───────── what it is');
const MIDDLE     = slice('<!-- ───────── what it is', '<!-- ───────── begin');

// ── 3. extract + clean the inline JS ──
let script = tpl.slice(tpl.indexOf('<script>') + '<script>'.length, tpl.indexOf('</script>'));
// 3a. strip the artifact-only tweaks panel IIFE (between its marker and smooth-nav)
const twkStart = script.indexOf('/* ───────── tweaks panel');
const navStart = script.indexOf('/* ───────── smooth nav');
script = script.slice(0, twkStart) + script.slice(navStart);
// 3b. replace the live Mirror's window.claude call with an in-browser curated reflection
const mirrorIdx = script.indexOf('live quantum mirror demo');
const tryIdx = script.indexOf('    try{', mirrorIdx);
const endIdx = script.indexOf("\n    out.classList.add('has');", tryIdx);
if (twkStart < 0 || navStart < 0 || tryIdx < 0 || endIdx < 0) {
  console.error('marker not found', { twkStart, navStart, tryIdx, endIdx }); process.exit(1);
}
const canned = `    // Curated reflection — a taste of the Mirror. The full Quantum Mirror lives
    // in the app, reading your own journal with your own key. Nothing typed here
    // is stored or sent anywhere; this preview is composed entirely in your browser.
    const REFLECTIONS = [
      "What I notice is a quiet readiness underneath the words \\u2014 the shape of someone already turning toward the thing, not away from it. There is no need to force the turn; it is happening at its own pace.",
      "There is a quality of holding here \\u2014 something carried carefully, perhaps longer than it needed to be. The pattern is not the weight itself, but the steadiness of the hands that have kept holding it.",
      "The shape of this is a threshold: one foot in the familiar, one in the not-yet. What I notice is that you named it at all, which is its own kind of crossing.",
      "What I notice is tenderness pointed inward, still finding its footing. The pattern is gentle attention learning to stay, even when staying is the harder thing.",
      "There is a quality of weather in this \\u2014 a state moving through, not a fixed fact about you. The pattern underneath is a witness that remains while the weather changes."
    ];
    const pick = REFLECTIONS[Math.floor(Math.random()*REFLECTIONS.length)];
    await new Promise(function(r){ setTimeout(r, 650); });
    reflection.textContent = pick;`;
script = script.slice(0, tryIdx) + canned + script.slice(endIdx);
const LANDING_SCRIPT = script.trim() + '\n';

// ── 4. emit server/landing.js ──
const J = s => JSON.stringify(s);
const out = `'use strict';
// Server-rendered marketing landing page for GET / (browser Accept: text/html).
// Adapted from the branded "standalone" design: artifact-only plumbing removed
// (tweaks panel, window.claude), inlined fonts swapped for the Google Fonts the
// landing CSP already allows, and real CTAs + live network stats wired in.
// GENERATED by scripts/build-landing.mjs from the design source — edit there.

const CSS = ${J(CSS)};
const INTRO_AURA = ${J(INTRO_AURA)};
const THRESHOLD = ${J(THRESHOLD)};
const MIDDLE = ${J(MIDDLE)};

// The single inline script, hash-pinned by the CSP in practice-room.js. Exported
// verbatim so the served bytes and the computed sha256 can never drift apart.
const LANDING_SCRIPT = ${J(LANDING_SCRIPT)};

const EXTRA_CSS = \`
  .nav .nav-dl{color:var(--gold-light)}
  .btn.ghost{background:none;color:var(--gold-light);border-color:var(--hairline-strong);box-shadow:none}
  .btn.ghost:hover{background:rgba(201,168,76,.07);box-shadow:none}
  .herocta{display:flex;gap:16px;justify-content:center;flex-wrap:wrap;margin-top:42px}
  .herostats{display:flex;justify-content:center;flex-wrap:wrap;margin-top:38px}
  .herostat{padding:0 28px;text-align:center}
  .herostat + .herostat{border-left:1px solid var(--hairline)}
  .herostat b{display:block;font-family:var(--serif);font-weight:400;font-size:32px;color:var(--gold-light);line-height:1}
  .herostat span{display:inline-block;margin-top:8px;font-size:9px;letter-spacing:.28em;text-transform:uppercase;color:var(--muted)}
  .beginctas{display:flex;gap:16px;justify-content:center;flex-wrap:wrap;margin:8px auto 0}
  .qrwrap{display:flex;flex-direction:column;align-items:center;gap:12px;margin-top:50px}
  .qrwrap img{width:132px;height:132px;border:1px solid var(--hairline);border-radius:10px;background:#f0d88a;padding:6px}
  .qrwrap .cap{font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:var(--muted)}
  .installnote{max-width:700px;margin:54px auto 0;border:1px solid var(--hairline);background:linear-gradient(180deg,var(--card),var(--card-2));padding:26px 30px;text-align:left}
  .installnote h4{font-family:var(--serif);font-weight:400;color:var(--gold);font-size:16px;letter-spacing:.06em;margin:0 0 12px}
  .installnote p{color:var(--muted);font-size:13px;margin:0 0 8px;line-height:1.7}
  .installnote strong{color:var(--silver);font-weight:400}
  .installnote em{color:var(--gold-light);font-style:italic}
  .installnote code{font-family:'SF Mono',Menlo,monospace;font-size:11.5px;color:var(--gold-light);background:rgba(0,0,0,.4);padding:2px 7px;border-radius:3px;word-break:break-all}
\`;

function esc(v){ return String(v == null ? '' : v).replace(/[&<>"']/g, function(c){ return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]; }); }
function fmtUptime(s){
  s = Math.max(0, Math.round(s || 0));
  const d = Math.floor(s/86400), h = Math.floor((s%86400)/3600), m = Math.floor((s%3600)/60);
  if (d) return d+'d '+h+'h';
  if (h) return h+'h '+m+'m';
  return m+'m '+(s%60)+'s';
}

function renderLanding(opts){
  opts = opts || {};
  const stats = opts.stats || { rooms: 0, feedSize: 0, uptime: 0 };
  const supportUrl = opts.supportUrl || '';
  const commit = opts.commit || 'main';

  const founder = supportUrl
    ? '<a class="btn ghost" href="' + esc(supportUrl) + '" target="_blank" rel="noopener">\\u25c8 Become a Founder \\u2197</a>'
    : '';

  const heroExtras =
    '      <div class="herocta">\\n' +
    '        <a class="btn" href="/download">Download for desktop <span aria-hidden="true">\\u2193</span></a>\\n' +
    '        <a class="btn ghost" href="/app">Open the web app <span aria-hidden="true">\\u2192</span></a>\\n' +
    '        ' + founder + '\\n' +
    '      </div>\\n' +
    '      <div class="herostats" aria-label="Live network">\\n' +
    '        <div class="herostat"><b>' + esc(stats.rooms) + '</b><span>In practice now</span></div>\\n' +
    '        <div class="herostat"><b>' + esc(stats.feedSize) + '</b><span>Transmissions</span></div>\\n' +
    '        <div class="herostat"><b>' + esc(fmtUptime(stats.uptime)) + '</b><span>Field uptime</span></div>\\n' +
    '      </div>';

  const hero = THRESHOLD.replace('    </div>\\n  </div>\\n</section>', '    </div>\\n' + heroExtras + '\\n  </div>\\n</section>');

  const liveLine = '<p class="topline" style="margin-top:14px;color:var(--gold)">\\u2726 ' +
    esc(stats.rooms) + ' in practice now \\u00b7 ' + esc(stats.feedSize) + ' transmissions shared</p>';
  const middle = MIDDLE.replace('Identity stays separable from practice.</p>', 'Identity stays separable from practice.</p>\\n        ' + liveLine);

  const begin =
'<section id="begin" class="begin" aria-labelledby="begin-h">\\n' +
'  <div class="wrap">\\n' +
'    <div class="reveal"><p class="eyebrow" style="justify-content:center"><svg class="glyph" viewBox="0 0 24 24"><path d="M12 2 L22 12 L12 22 L2 12 Z" fill="currentColor"></path></svg> <span class="num">VII \\u00b7</span> Begin</p></div>\\n' +
'    <h2 id="begin-h" class="reveal" style="--d:120ms;text-align:center">Your <em class="gold">first three movements.</em></h2>\\n' +
'    <div class="reveal" style="--d:200ms"><p class="lead" style="margin:0 auto;text-align:center">Open the app \\u00b7 set one intention \\u00b7 let the Council recommend your first session.<br><em class="gold">The field is already open.</em></p></div>\\n' +
'    <div class="threesteps reveal" style="--d:300ms">\\n' +
'      <div class="step3"><div class="n">i.</div><h4>Arrive</h4><p>One guided breath. No account required to begin.</p></div>\\n' +
'      <div class="step3"><div class="n">ii.</div><h4>Set one intention</h4><p>Plain language. The Council listens, you stay in charge.</p></div>\\n' +
'      <div class="step3"><div class="n">iii.</div><h4>Practice</h4><p>Receive your attuned session and step into the field.</p></div>\\n' +
'    </div>\\n' +
'    <div class="beginctas reveal" style="--d:360ms">\\n' +
'      <a class="btn" href="/download">Download for desktop <span aria-hidden="true">\\u2193</span></a>\\n' +
'      <a class="btn ghost" href="/app">Open the web app <span aria-hidden="true">\\u2192</span></a>\\n' +
'      ' + founder + '\\n' +
'    </div>\\n' +
'    <div class="qrwrap reveal" style="--d:420ms">\\n' +
'      <img src="/qr-app.svg" alt="QR code to open the Gateway Protocol web app on your phone" width="132" height="132">\\n' +
'      <span class="cap">Scan to open on your phone</span>\\n' +
'    </div>\\n' +
'    <div class="installnote reveal" style="--d:480ms">\\n' +
'      <h4>Installing the desktop app</h4>\\n' +
'      <p>Native builds for <strong>macOS (Intel &amp; Apple Silicon)</strong>, <strong>Windows</strong>, and <strong>Linux</strong>. The app is not yet code-signed, so the first launch may warn that the developer cannot be verified \\u2014 that is expected.</p>\\n' +
'      <p><strong>macOS:</strong> right-click the app \\u2192 <em>Open</em>, or open System Settings \\u2192 Privacy &amp; Security and click <em>Open Anyway</em>. Or in Terminal: <code>xattr -dr com.apple.quarantine "/Applications/Gateway Protocol.app"</code></p>\\n' +
'      <p>It launches normally after that \\u2014 the prompt only appears once.</p>\\n' +
'    </div>\\n' +
'  </div>\\n' +
'</section>';

  const footer =
'<footer>\\n' +
'  <svg class="glyph-lg" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 L22 12 L12 22 L2 12 Z M12 7 L17 12 L12 17 L7 12 Z" fill="currentColor" stroke="none"></path></svg>\\n' +
'  <div class="trail">Gateway Protocol \\u00b7 Consciousness \\u00b7 Healing \\u00b7 Abundance \\u00b7 Liberation \\u00b7 Owned, not subscribed.</div>\\n' +
'  <p class="discl">This platform supports practice; it does not diagnose, treat, or cure. Not medical advice. Coherence is estimated from breathing rhythm \\u2014 a contemplative proxy, not a clinical HRV reading. Solfeggio and frequency associations are contemplative / traditional framings, not established clinical fact.</p>\\n' +
'  <div class="trail" style="margin-top:30px">\\u00a9 MMXXVI \\u00b7 Made for the long quiet \\u00b7 build ' + esc(commit) + '</div>\\n' +
'</footer>';

  const nav =
'<header class="chrome">\\n' +
'  <a class="mark" href="#top" aria-label="Gateway Protocol">\\n' +
'    <svg class="glyph" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 L22 12 L12 22 L2 12 Z M12 7 L17 12 L12 17 L7 12 Z" fill="currentColor" stroke="none"></path></svg>\\n' +
'    <span>Gateway Protocol</span>\\n' +
'  </a>\\n' +
'  <nav class="nav" aria-label="Primary">\\n' +
'    <a href="#what">What it is</a>\\n' +
'    <a href="#council">Council</a>\\n' +
'    <a href="#protocol">Protocol</a>\\n' +
'    <a href="#platform">Platform</a>\\n' +
'    <a href="#waves">Waves</a>\\n' +
'    <a href="#sovereign">Sovereignty</a>\\n' +
'    <a class="nav-dl" href="/download">Download</a>\\n' +
'  </nav>\\n' +
'</header>\\n' +
'<div class="scrollcue" id="scrollcue"><span>Scroll</span><span class="line"></span></div>';

  return '<!doctype html>\\n<html lang="en">\\n<head>\\n' +
    '<meta charset="utf-8">\\n' +
    '<title>The Gateway Protocol \\u2014 A sovereign space for consciousness practice</title>\\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1">\\n' +
    '<meta name="description" content="A sovereign, local-first platform for structured consciousness practice \\u2014 the Monroe Gateway Process, a Council of Five, frequency layering, and an optional anonymous community. Owned, not subscribed.">\\n' +
    '<meta name="theme-color" content="#02020a">\\n' +
    '<meta property="og:title" content="The Gateway Protocol">\\n' +
    '<meta property="og:description" content="A sovereign space for consciousness practice. Owned, not subscribed.">\\n' +
    '<meta property="og:type" content="website">\\n' +
    '<link rel="preconnect" href="https://fonts.googleapis.com">\\n' +
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\\n' +
    '<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&family=Montserrat:wght@200;300;400;500&display=swap" rel="stylesheet">\\n' +
    '<style>' + CSS + '</style>\\n<style>' + EXTRA_CSS + '</style>\\n</head>\\n' +
    '<body data-motion="cinematic">\\n' +
    INTRO_AURA + nav + hero + middle + begin + footer +
    '\\n<script>' + LANDING_SCRIPT + '</script>\\n</body>\\n</html>';
}

module.exports = { LANDING_SCRIPT, renderLanding };
`;

fs.writeFileSync('server/landing.js', out);
console.log('wrote server/landing.js', out.length, 'bytes');
console.log('LANDING_SCRIPT', LANDING_SCRIPT.length, 'bytes  CSS', CSS.length, '  MIDDLE', MIDDLE.length);
